import { ReproductionEvent } from "@/types/reproduction_event.type";
import { RxJsonSchema } from "rxdb";

export const reproductionEventSchema: RxJsonSchema<ReproductionEvent> = {
  title: "reproduction schema",
  version: 1,
  primaryKey: "event_id",
  type: "object",
  properties: {
    event_id: { type: "string", maxLength: 36 },
    rgn: { type: "string", maxLength: 10 },
    event_type: { type: "string", maxLength: 10 },
    productive_status: { type: "string", maxLength: 20 },
    age: { type: "number" },
    evaluation_date: { type: "string", format: "date" },
    body_score: { type: "integer", minimum: 1, maximum: 5 },
    gestational_condition: { type: "string", maxLength: 20 },
    ovary_size: { type: "string", maxLength: 20 },
    ovary_structure: { type: "string", maxLength: 20 },
    cycle_stage: { type: "string", maxLength: 20 },
    protocol_name: { type: "string" },
    d0_date: { type: "string", format: "date" },
    d8_date: { type: "string", format: "date" },
    d10_date: { type: "string", format: "date" },
    d11_date: { type: "string", format: "date" },
    bull_name: { type: "string" },
    d22_date: { type: "string", format: "date" },
    d30_date: { type: "string", format: "date" },
    diagnostic_d30: { type: "string", maxLength: 20 },
    d32_date: { type: "string", format: "date" },
    resync_bull: { type: "string" },
    calving_start_date: { type: "string", format: "date" },
    calving_end_date: { type: "string", format: "date" },
    natural_mating_d35_entry: { type: "string", format: "date" },
    natural_mating_bull: { type: "string" },
    natural_mating_d80_exit: { type: "string", format: "date" },
    d110_date: { type: "string", format: "date" },
    final_diagnostic: { type: "string", maxLength: 20 },
    pregnancy_origin: { type: "string", maxLength: 20 },
    created_at: { type: "number" },
    updated_at: { type: "number" },
    _deleted: { type: "boolean" },
  },
  required: [
    "event_id",
    "rgn",
    "event_type",
    "d0_date",
    "_deleted",
    "created_at",
    "updated_at",
  ],
  indexes: ["rgn", "event_type"],
};
